
package org.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MyDataException", targetNamespace = "http://myservice.ws.org/")
public class MyDataException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MyDataException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MyDataException_Exception(String message, MyDataException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MyDataException_Exception(String message, MyDataException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.ws.client.MyDataException
     */
    public MyDataException getFaultInfo() {
        return faultInfo;
    }

}
