
package org.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyHello", targetNamespace = "http://myservice.ws.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyHello {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://myservice.ws.org/", className = "org.ws.client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://myservice.ws.org/", className = "org.ws.client.HelloResponse")
    @Action(input = "http://myservice.ws.org/MyHello/helloRequest", output = "http://myservice.ws.org/MyHello/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kali", targetNamespace = "http://myservice.ws.org/", className = "org.ws.client.Kali")
    @ResponseWrapper(localName = "kaliResponse", targetNamespace = "http://myservice.ws.org/", className = "org.ws.client.KaliResponse")
    @Action(input = "http://myservice.ws.org/MyHello/kaliRequest", output = "http://myservice.ws.org/MyHello/kaliResponse")
    public double kali(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param nim
     * @return
     *     returns org.ws.client.Mahasiswa
     * @throws MyDataException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataMahasiswa", targetNamespace = "http://myservice.ws.org/", className = "org.ws.client.GetDataMahasiswa")
    @ResponseWrapper(localName = "getDataMahasiswaResponse", targetNamespace = "http://myservice.ws.org/", className = "org.ws.client.GetDataMahasiswaResponse")
    @Action(input = "http://myservice.ws.org/MyHello/getDataMahasiswaRequest", output = "http://myservice.ws.org/MyHello/getDataMahasiswaResponse", fault = {
        @FaultAction(className = MyDataException_Exception.class, value = "http://myservice.ws.org/MyHello/getDataMahasiswa/Fault/MyDataException")
    })
    public Mahasiswa getDataMahasiswa(
        @WebParam(name = "nim", targetNamespace = "")
        String nim)
        throws MyDataException_Exception
    ;

}
